name = "stock-now"
compatibility_date = "2025-03-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "stock-now-database"
database_id = "9b2b4c73-4743-4740-aaca-8a79f5f7f2b0"
migrations_dir = "migrations"
