name = "stock-now-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

# Cloudflare D1 데이터베이스 바인딩
[[d1_databases]]
binding = "DB"
database_name = "stock-now-db"
database_id = "32ab9af0-73b8-49b9-87df-fab641276b6f"
